const hpQuestion = [
    {
        question:"What is your favorite type of animal?", 
        answers:["Badger", "Raven", "Snake", "Lion"],
        gryfAnswer:"Lion",
        slythAnswer: "Snake",
        huffAnswer:'Badger',
        ravAnswer:'Raven',
        questionId: '1456898',
    },
    {
        question:"What is your greatest personal attribute?", 
        answers:["Cunning", "Loyalty", "Intelligence", "Being a Badger"],
        gryfAnswer:"Loyalty",
        slythAnswer: "Cunning",
        huffAnswer:'Being a Badger',
        ravAnswer:'Intelligence',
        questionId: '1456897',
    },
    {
        question:"What is your favorie color?", 
        answers:["Red", "Blue", "Yellow", "Green"],
        gryfAnswer:"Red",
        slythAnswer: "Green",
        huffAnswer:'Yellow',
        ravAnswer:'Blue',
        questionId: '1456896',
    },
    {
        question:"When you're dead, what do you want people to do when they think of you?", 
        answers:["Tell stories about me", "Think of my achievements", "Miss me and smile", "I don't care what people think of me when I'm dead; it's when I'm alive that counts."],
        gryfAnswer:"Tell stories about me",
        slythAnswer: "I don't care what people think of me when I'm dead; it's when I'm alive that counts.",
        huffAnswer:'Miss me and smile',
        ravAnswer:'Think of my achievements',
        questionId: '1456893',
    },
    {
        question:"What position in Qudditch would you most like to play?", 
        answers:["Bludger", "Keeper", "Seeker", "Chaser"],
        gryfAnswer:"Seeker",
        slythAnswer: "Bludger",
        huffAnswer:'Keeper',
        ravAnswer:'Chaser',
        questionId: '1456894',        
    },
    {
        question:"What would you have done with Hagrid's Dragon?", 
        answers:["Told Dumbledore", "Raised it Yourself", "Let it Go", "Given it to the appropriate department at the Ministry of Magic"],
        gryfAnswer:"Raised it Yourself",
        slythAnswer: "Told Dumbledore",
        huffAnswer:'Given it to the appropriate department at the Ministry of Magic',
        ravAnswer:'Let it Go',
        questionId: '1456892',
    },
    {
        question:"What class would you most like to attend?", 
        answers:["Potions", "Defense Against the Dark Arts", "Charms", "Herbology and the Study of Plants"],
        gryfAnswer:"Defense Against the Dark Arts",
        slythAnswer: "Potions",
        huffAnswer:'Herbology and the Study of Plants',
        ravAnswer:'Charms',
        questionId: '1456894',
    },
    {
        question:"What is your favorie Bertie Bott's Bean flavor?", 
        answers:["Dirt", "Earwax", "Soap", "Vomit"],
        gryfAnswer:"Earwax",
        slythAnswer: "Vomit",
        huffAnswer:'Grass',
        ravAnswer:'Dirt',
        questionId: '1456896',
    },
];
    
export default (n = 5) => 
    Promise.resolve(hpQuestion.sort(() => 0.5 - Math.random()).slice(0,n));